---
title: "Predicting graduation rates"
output: github_document
---

```{r}
library(tidyverse)
library(tidymodels)
```


ELS Data needs to be downloaded from:

https://nces.ed.gov/EDAT/Data/Zip/ELS_2002-12_PETS_v1_0_Student_R_Datasets.zip

The zip file needs to opened up in your working directory so the code below will work. 

## Directory structure
```{r}
rddir<-"../../data/raw/"
cddir<-"../../data/cleaned/"
```

## Pipe Function
```{r}
## Ben: what's the pipe function for paste0? could use it here
```


```{r}
# Load R Data File
if(file.exists(paste0(cddir,"els.Rds"))==FALSE){

load(paste0(rddir,"els_02_12_byf3pststu_v1_0.rdata"))

els<-els_02_12_byf3pststu_v1_0

rm(els_02_12_byf3pststu_v1_0)

names(els)<-tolower(names(els))

# Create vector of selected variables
keepvars <- tolower(c(
   "stu_id", ## Student ID
   "sch_id", ## School ID
   "strat_id", ## Stratum ID
   "psu", ## Primary sampling unit
   "BYRACE", ##  Race
   "BYSES1", ## SEs
   "BYINCOME", ## Income
   "BYPARED", ## Parental Education
   "BYNELS2M", ## Math Score
   "BYNELS2R", ## Reading Score
   "F3ATTAINMENT", ## Atainment
   "F2PS1SEC" ##First inst attended
   ))

keepvars<-tolower(keepvars)

els%>%
   select(one_of(keepvars))->els


save(els,file=paste0(cddir,"els.Rds"))
} else {
load(paste0(cddir,"els.rds"))
}
```

## Recoding 
```{r}

## recode all less than -3 as missing
els<-els%>%mutate_all( ~ifelse(.x< (-3) , NA, .x))

## Only people who started at four years

els<-els%>%filter(f2ps1sec%in%c(1:3))

## create variable for completing a ba

els%>%
   mutate(ba_complete=ifelse(f3attainment%in%c(6,7,8,10),1,0))->els

## average bachelor's completion overall

els%>%summarize(mean(ba_complete))


```

## Split to analysis data
```{r}

##Need to generalize, want a better process for vars
els%>%
   select(ba_complete,
          one_of(keepvars[-(1:4)]),
          -byses1,
          -f3attainment,
          -f2ps1sec 
          )->els_a

```

```{r}
## set factor variables


## Number of unique values
few_unique<-function(x){
  ifelse(length(unique(x))<20,
         TRUE,
         FALSE)}

## Quickly identify likely factor variables
els_a%>%
   select_if( ~ (few_unique(.)))%>%
   names(.)->likely_factors

## Mutate to be factors
els_a%>%
   mutate_at(.vars=likely_factors,.funs=as_factor)->els_a

```


## Formula
```{r}
grad_rec<-recipe(ba_complete~.,
                 data=els_a)
```


## Pre Processing

### Imputation
```{r}
imputed<-
   grad_rec%>%
   step_knnimpute(all_predictors())
```


### Dummy Variables
```{r}
ind_vars<-imputed%>%
   step_dummy(all_predictors(),-bynels2r,-bynels2m,)
```


### Scaling
```{r}
standardized <- ind_vars %>%
  step_center(all_predictors())  %>%
  step_scale(all_predictors()) 
```


```{r}
trained_rec <- prep(standardized, training = els_a)
```

```{r}
train_data<-bake(trained_rec, new_data =els_a)
```

```{r}

logit_fit<-logistic_reg(mode="classification")%>%
  set_engine("glm")%>%
  fit(ba_complete~.,data=juice(trained_rec))

```

```{r}
logit_fit$fit%>%summary()
```




